---
title: "How to install CellEnrich"
author: "Hai Nguyen"
date : "2024.06.20"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to install CellEnrich}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

-   Testing Environment

1.  Ubuntu 22.04.2 LTS
2.  R version 4.2.0
3.  RStudio 2023.03.0+386 "Cherry Blossom"
4.  Rtools 40

-   This installation guide is written in R version 4.2.0

## Install Dependent Packages

-   Also some package needs **install from sources which needs compilation** and it needs proper version of [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed

-   It's recommended to install `devtools`, `BiocManager` packages first, to install following packages in Github / Bioconductor (not in CRAN).

``` r
library(devtools)
library(BiocManager)
```

------------------------------------------------------------------------

As noted in [README](https://github.com/unistbig/CellEnrich)

`CellEnrich` needs some packages to be installed before using it.

Bioconductor Packages

1.  `SingleCellExperiment`
2.  `scran`

``` r
BiocManager::install('SingleCellExperiment')
BiocManager::install('scran')
```

Other Packages

1.  `waiter`
2.  `ggbiplot`
3.  `farver`

``` r
devtools::install_github('JohnCoene/waiter')
devtools::install_github('vqv/ggbiplot')
install.packages('farver') # install 'farver' if not installed.

remotes::install_github('noobCoding/CellEnrich')
```

After installing these packages:

## Install CellEnrich

Running this Script will install most of the dependent packages.

``` r
install_github('noobCoding/CellEnrich')

library(CellEnrich)
```

------------------------------------------------------------------------

## Download Data

CellEnrich provides example data and genesets.

using this function, users can download them in the current working directory.

``` r
CellEnrich::DownloadData(type='test') # for available human related data & genesets 

## Use type='all' for all available data
```

Here is a list of data.

-   Human Gene-sets

    -   "Reactome_2022.RData"
    -   "WikiPathways_2021_Human.RData"
    -   "KEGG_2021_Human.RData"
    -   "humanGO.RData"
    -   "humanGOBP.RData"
    -   "humanGOCC.RData"
    -   "humanGOMF.RData"

-   Mouse Gene-sets

    -   "WikiPathways_2019_Mouse.RData"
    -   "KEGG_2021_Mouse.RData"
    -   "mouseGO.RData"
    -   "mouseGOBP.RData"
    -   "mouseGOCC.RData"
    -   "mouseGOMF.RData"

-   Human Data

    -   "pbmcClustInfo.RData" ([Seurat PBMC Guide](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html))

    -   "pbmcData.RData"

    -   [DuoClustering](https://bioconductor.org/packages/release/data/experiment/html/DuoClustering2018.html)([link](https://f1000research.com/articles/7-1141))

    -   "koh.RData"

    -   "kohInfo.RData"

-   [Mouse Data](https://satijalab.org/seurat/v3.1/mca.html)
